import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className='h-full mt-20'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-4xl text-blue-800 text-center animate-pulse'>
        This App has been generated with{' '}
        <span className='text-5xl text-red-300'>Create Next App</span> and
        Bootstraped With
        <span className='text-5xl text-red-300'>Tailwind</span>.
      </h1>
    </div>
  );
}
